title: Video Processing | Graphics and Multimedia Laboratory CMC MSU
email: info@compression.ru
description: >-
  Everything about video processing: codecs, filters, quality measures, matting, completion.
  MSU CMC, Graphics and Multimedia Laboratory, Video Group
baseurl: ""
url: "https://videoprocessing.ai"
google_analytics: 'UA-15281510-2'

collections:
  projects:
    output: true
  subprojects:
    output: true
  carousel:
    output: false

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      tag: visible
      see_also: []
  - scope:
      path: "_posts/codecs"
    values:
      permalink: /codecs/:categories/:title:output_ext
      project: codecs
  - scope:
      path: "_posts/vqmt"
    values:
      permalink: /vqmt/:categories/:title:output_ext
      project: vqmt
      layout: "vqmt-post"
  - scope:
      path: "_posts/vqmt3d"
    values:
      permalink: /stereo_quality/:categories/:title:output_ext
      project: vqmt3d
  - scope:
      path: "_posts/benchmarks"
    values:
      permalink: /benchmarks/:categories/:title:output_ext
      project: benchmarks
  - scope:
      path: "_posts/filters"
    values:
      permalink: /video_filters/:categories/:title:output_ext
      project: filters
  - scope:
      path: "_posts/datasets"
    values:
      permalink: /datasets/:categories/:title:output_ext
      project: datasets
  - scope:
      path: "_posts/other"
    values:
      permalink: /other/:categories/:title:output_ext
      project: other
  - scope:
      path: "_posts/metrics"
    values:
      permalink: /metrics/:categories/:title:output_ext
      project: metrics
  - scope:
      type: "projects"
    values:
      layout: "project"
  - scope:
      type: "subprojects"
    values:
      layout: "subproject"
  - scope:
      path: "about"
    values:
      layout: "about"

# Build settings
markdown: kramdown
kramdown:
   math_engine: mathjax
   
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate-v2
  - jekyll-sitemap
  - jekyll-youtube
  - jekyll-tidy
  - jekyll-redirect-from

exclude:
  - .idea
  - vendor  # for GitLab CI
  - .sass-cache
  - README.md
  - Gemfile
  - Gemfile.lock

pagination:
  enabled: true
  per_page: 24
  permalink: '/page/:num/'
  title: ':title - page :num'
  sort_field: 'date'
  sort_reverse: true
  tag: visible
